export interface IQuestion {
  min?: number;
  getValidators?: any;
  key: number,
  value: any,
  controlType: any,
  label: any,
  type?: string,
  required?: boolean;
  validators?: any[];
  columnName: string;
  minLength?: number;
  maxLength?: number;
  pattern: string;
  options?: any[];
  minDate?: string;
  maxDate?: string;
  fileExtension?: string[];
  fileExtensionValidationMessage?: string;
  fileValues?: any[];
  deletedFileValue?: any[];
  multiple?: boolean,
  fileSize?: number,
  optionsParentColumn?: any,
  dependentCondition?: string[],
  selectAllOption?: boolean;
  allChecked?: boolean;
  disabled?: boolean,
  childQuestionModels?: any;
  groupParentId?: string;
  indexNumberTrack?: string;
  serialNumb?: string;
  parentColumns?: string;
  placeHolder?: string;
  currentDate?: string;
  removable?: boolean;
  infoAvailable?: boolean;
  infoMessage?: string;
  max?: number;
}